<h2> Réserver une table </h2>

<form action="" method="post" class="generic-form">
            <fieldset>
        <legend>
        <i class="fas fa-edit"></i> Votre réservation
        </legend>
        <ul>
            <li>
                <label for="date">Date de réservation</label>
                <input type="date" id="date" name="date" value="">
            </li>
            <li>
                <label for="time">Heure de réservation</label>
                <input type="time" id="time" name="time" value="">
            </li>
            <li>
                <label for="couvert">Nombre de couvert(s)</label>
                <select name="couvert" id="couvert">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                </select>
            </li>
           
            </fieldset>
            
               
            <button class="button button-primary" type="submit" id="creer">Valider</button>
            <button class="button button-cancel" type="submit" id="supprimer">Annuler</button>
    </fom>
