<h2><i class="fas fa-lock " aria-hidden="true"></i> Se connecter avec un compte utilisateur</h2>

<form action="" method="post" class="generic-form">
            
            <fieldset>
                <legend>
                <i class="fas fa-lock"></i> Informations d'autendification
                </legend>
                <ul>
                    <li>
                        <label for="mail">E-mail :</label>
                        <input type="text" name="e_mail" id="mail" value="" placeholder="exemple@gmail.com">
                    </li>
                    <li>
                        <label for="mdp">Mot de passe :</label>
                        <input type="password" name="mdp" id="mdp" value="">
                    </li>
                </ul>
            </fieldset>
            <button class="button button-primary" type="submit" id="creer">Connexion</button>
            <button class="button button-cancel" type="reset" id="supprimer">Annuler</button>
    </fom>
