<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant"><!--Restaurant - Made In America !-->Bonjour Yann!
        </a>
    </h1>
</header>
<?php if(isset($_SESSION['connexion'])): ?>
<!-- Interface utilisateur -->

<h2>Bonjour <?= $_SESSION['prenom'] ?></h2>
<?php endif ?>
<nav class="user-interface">

    <ul class="link-list">
        <!-- Code HTML/PHP à écrire -->
        <?php if(!isset($_SESSION['connexion'])){ ?>
       <li>
            <a class="button button-primary" href="<?= $requestUrl ?>/user">Crée un compte</a>
       </li> 
       <li>
            <a class="button button-primary" href="<?= $requestUrl ?>/user/login">Connexion</a>
       </li>
        <?php }elseif($_SESSION['admin']== 1){ ?>
        <li>
            <a class="button button-primary" href="<?= $requestUrl ?>/admin/table">Listes réservation</a>
        </li>
        <li>
            <a class="button button-primary" href="<?= $requestUrl ?>/admin/meal">Listes commandes</a>
        </li>
        <li>
            <a class="button button-primary" href="<?= $requestUrl ?>/admin/users">Listes clients</a>
        </li>
        <li>
            <a class="button button-primary" href="<?= $requestUrl ?>/admin/addmeal">Ajouter un nouveau produit</a>
        </li>
        <li>
            <a class="button button-cancel" href="<?= $requestUrl ?>/admin/users">Désactiver un compte</a>
        </li>
        <li>
            <a class="button button-cancel" href="<?= $requestUrl ?>/user/logout">Deconnexion</a>
       </li>
        <?php }else{ ?>
       <li>
            <a class="button button-primary" href="<?= $requestUrl ?>/booking">Réservation</a>
            <a class="button button-primary" href="<?= $requestUrl ?>/order">Commander</a>
            <a class="button button-primary" href="<?= $requestUrl ?>/basket">Mes commandes</a>
       </li>
       <li>
            <a class="button button-cancel" href="<?= $requestUrl ?>/user/logout">Deconnexion</a>
       </li> 
        <?php } ?>
    </ul>
    
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>